services:
  php:
    container_name: devwp_php
    build:
      context: ./config/php
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    expose:
      - 9000
    volumes:
      - ~/www:/src/www:rw
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./config/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./config/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    healthcheck:
      test: ['CMD-SHELL', 'pidof php-fpm || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mariadb:
    container_name: devwp_mariadb
    image: mariadb:latest
    environment:
      MARIADB_ROOT_HOST: '%'
      MARIADB_ROOT_PASSWORD: root
      MARIADB_AUTO_UPGRADE: true
      TZ: Europe/Stockholm
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - '3306:3306'
    command: --bind-address=0.0.0.0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'mariadb-admin', 'ping', '-h', 'localhost', '-u', 'root', '-proot']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    container_name: devwp_redis
    image: redis:alpine
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  nginx:
    container_name: devwp_nginx
    build:
      context: ./config/nginx
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    ports:
      - '80:80'
      - '443:443/tcp'
      - '443:443/udp'
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/global/:/etc/nginx/global/:ro
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./config/nginx/sites-enabled/:/etc/nginx/sites-enabled/:rw
      - ./config/certs:/certs:ro
      - ~/www:/src/www:rw
    depends_on:
      php:
        condition: service_healthy
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
      certs:
        condition: service_completed_successfully
      mailpit:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'nginx', '-t']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  certs:
    container_name: devwp_certs
    image: stakater/ssl-certs-generator
    volumes:
      - ./config/certs:/certs

  mailpit:
    container_name: devwp_mailpit
    image: axllent/mailpit
    expose:
      - '1025:1025' # smtp server
    ports:
      - '8025:8025' # web ui
    environment:
      - TZ=Europe/Stockholm
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost:8025/api/v1/info']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  sonarqube:
    container_name: devwp_sonarqube
    image: sonarqube:community
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    expose:
      - 9000
    ports:
      - '9000:9000'
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost:9000/api/system/status'
        ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s

  sonarqube-scanner:
    container_name: devwp_sonarqube-scanner
    image: sonarsource/sonar-scanner-cli:latest
    volumes:
      - ~/www:/usr/src:r
    depends_on:
      sonarqube:
        condition: service_healthy
    environment:
      - SONAR_TOKEN=${SONAR_TOKEN:-}
    # Example entrypoint for manual token-based scanning:
    # entrypoint: [
    #   "sonar-scanner",
    #   "-Dsonar.projectKey=example_project",
    #   "-Dsonar.sources=/usr/src/example.test",
    #   "-Dsonar.host.url=http://sonarqube:9000",
    #   "-Dsonar.token=${SONAR_TOKEN}"
    # ]

  seonaut:
    build:
      context: ./config/seonaut
    container_name: 'devwp_seonaut'
    ports:
      - '9001:9001'
    depends_on:
      mariadb:
        condition: service_healthy
      sonarqube:
        condition: service_started
    command: sh -c "/bin/wait && /app/seonaut"
    environment:
      - WAIT_HOSTS=mariadb:3306
      - WAIT_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost:9001']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
volumes:
  mariadb:
  redis:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
