services:
  php:
    container_name: devwp_php
    build:
      context: ./config/php
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    expose:
      - 9000
    depends_on:
      - database
      - cache
    volumes:
      - ./www:/src/www:rw
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./config/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./config/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini

  database:
    container_name: devwp_database
    image: mysql:innovation
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database:/var/lib/mysql
    ports:
      - '3306:3306'

  cache:
    container_name: devwp_cache
    image: redis:alpine
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data

  web:
    container_name: devwp_web
    build:
      context: ./config/nginx
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    ports:
      - '80:80'
      - '443:443/tcp'
      - '443:443/udp'
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/global/:/etc/nginx/global/:ro
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./config/nginx/sites-enabled/:/etc/nginx/sites-enabled/:rw
      - ./config/certs:/certs:ro
      - ./www:/src/www:rw
    depends_on:
      - php
      - certs

  certs:
    container_name: devwp_certs
    image: stakater/ssl-certs-generator
    volumes:
      - ./config/certs:/certs

  mailhog:
    container_name: devwp_mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  sonarqube:
    container_name: devwp_sonarqube
    image: sonarqube:community
    expose:
      - 9000
    ports:
      - '9000:9000'

  sonarqube-scanner:
    container_name: devwp_sonarqube-scanner
    image: sonarsource/sonar-scanner-cli:latest
    volumes:
      - ./www:/usr/src:r
    entrypoint: [
      "sonar-scanner",
      "-Dsonar.projectKey=cirkulation",
      "-Dsonar.sources=cirkulation.test",
      "-Dsonar.host.url=http://sonarqube:9000",
      "-Dsonar.token=sqp_7469b2ba5c18b21d78ded586c997fff84dd7c73d"
    ]
volumes:
  database:
  cache:
