services:
  php:
    build: ./config/php
    expose:
      - 9000
    depends_on:
      - database
      - cache
    ports:
      - '9003:9003' # xdebug

  database:
    image: mysql:innovation
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - database:/var/lib/mysql
    ports:
      - '3306:3306'

  cache:
    image: redis:alpine
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data

  web:
    build: ./config/nginx
    environment:
      - DOMAINS=${DOMAINS}
    ports:
      - '80:80'
      - '443:443/tcp'
      - '443:443/udp'
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/global/:/etc/nginx/global/:ro
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./config/nginx/sites-enabled/:/etc/nginx/sites-enabled/:ro
      - ./config/nginx/cache:/var/cache/nginx:rw
      - ./config/certs:/certs:ro
      - ./www:/src/www
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - php
      - certs

  certs:
    image: stakater/ssl-certs-generator
    environment:
      - SSL_SUBJECT=${DOMAINS}
    volumes:
      - ./config/certs:/certs

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
volumes:
  database:
  cache:
