services:
  php:
    container_name: devwp_php
    build:
      context: ./config/php
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    expose:
      - 9000
    volumes:
      - ./www:/src/www:rw
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./config/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./config/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini

  mariadb:
    container_name: devwp_mariadb
    image: mariadb:12.0.1-rc
    environment:
      MARIADB_ROOT_HOST: '%'
      MARIADB_ROOT_PASSWORD: root
      MARIADB_AUTO_UPGRADE: true
      MARIADB_DATABASE: devwp
      TZ: Europe/Stockholm
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - '3306:3306'
    command: --bind-address=0.0.0.0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

  redis:
    container_name: devwp_redis
    image: redis:alpine
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - redis:/data

  web:
    container_name: devwp_web
    build:
      context: ./config/nginx
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    ports:
      - '80:80'
      - '443:443/tcp'
      - '443:443/udp'
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/global/:/etc/nginx/global/:ro
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./config/nginx/sites-enabled/:/etc/nginx/sites-enabled/:rw
      - ./config/certs:/certs:ro
      - ./www:/src/www:rw
    depends_on:
      - php
      - mariadb
      - redis
      - certs
      - sonarqube
      - mailpit

  certs:
    container_name: devwp_certs
    image: stakater/ssl-certs-generator
    volumes:
      - ./config/certs:/certs

  mailpit:
    container_name: devwp_mailpit
    image: axllent/mailpit
    expose:
      - '1025:1025' # smtp server
    ports:
      - '8025:8025' # web ui
    environment:
      - TZ=Europe/Stockholm
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1

  sonarqube:
    container_name: devwp_sonarqube
    image: sonarqube:community
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    expose:
      - 9000
    ports:
      - '9000:9000'

  sonarqube-scanner:
    container_name: devwp_sonarqube-scanner
    image: sonarsource/sonar-scanner-cli:latest
    volumes:
      - ./www:/usr/src:r
    depends_on:
      - sonarqube
    # entrypoint: [
    #   "sonar-scanner",
    #   "-Dsonar.projectKey=cirkulation",
    #   "-Dsonar.sources=cirkulation.test",
    #   "-Dsonar.host.url=http://sonarqube:9000",
    #   "-Dsonar.token=sqp_7469b2ba5c18b21d78ded586c997fff84dd7c73d"
    # ]
volumes:
  mariadb:
  redis:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
