services:
  php:
    container_name: sites_php
    build:
      context: ./config/php
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    expose:
      - 9000
    depends_on:
      - database
      - cache
    volumes:
      - ./www:/src/www
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro

  database:
    container_name: sites_database
    image: mysql:innovation
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - database:/var/lib/mysql
    ports:
      - '3306:3306'

  cache:
    container_name: sites_cache
    image: redis:alpine
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data

  web:
    container_name: sites_web
    build:
      context: ./config/nginx
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    environment:
      - DOMAINS=${DOMAINS}
    ports:
      - '80:80'
      - '443:443/tcp'
      - '443:443/udp'
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/global/:/etc/nginx/global/:ro
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./config/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./config/nginx/cache:/var/cache/nginx:rw
      - ./config/certs:/certs:ro
      - ./www:/src/www
    depends_on:
      - php
      - certs

  certs:
    container_name: sites_certs
    image: stakater/ssl-certs-generator
    environment:
      - SSL_SUBJECT=${DOMAINS}
    volumes:
      - ./config/certs:/certs

  mailhog:
    container_name: sites_mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
volumes:
  database:
  cache:
