name: Update Dependencies

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2 AM UTC
  workflow_dispatch: # Optional manual trigger

# Add permissions block to allow pushing changes
permissions:
  contents: write

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Update dependencies in package.json
        run: bunx npm-check-updates -u

      - name: Install updated dependencies and generate bun.lockb
        run: bun install

      - name: Commit and push changes
        run: |
          # Use github context for actor info for consistency
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          # Check if there are staged changes before committing
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: Auto-update dependencies and lockfile"
            git push # Rely on checkout action's token configuration
          fi
