name: Update Dependencies

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2 AM UTC
  workflow_dispatch: # Optional manual trigger

# Add permissions block to allow pushing changes
permissions:
  contents: write

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Update dependencies in package.json
        run: bunx npm-check-updates -u

      - name: Install updated dependencies and generate bun.lock
        run: bun install

      - name: Run unit tests
        run: bun run test:run
        timeout-minutes: 10

      - name: Generate coverage report
        run: bun run test:coverage
        timeout-minutes: 10
        continue-on-error: true

      - name: Start Docker services for integration tests
        run: docker compose up -d mariadb
        timeout-minutes: 5

      - name: Wait for MariaDB
        run: |
          timeout 30 bash -c 'until docker exec devwp_mariadb mariadb-admin ping -h localhost -u root -proot; do sleep 1; done'

      - name: Run integration tests
        run: bun run test:integration
        timeout-minutes: 15

      - name: Stop Docker services
        if: always()
        run: docker compose down

      - name: Run test build
        run: bun run build
        timeout-minutes: 10

      - name: Commit changes
        id: commit # Add an id to check output later
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add package.json bun.lock # Be specific about files to add
          # Check if there are staged changes before committing
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "changes_exist=false" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected, committing..."
            git commit -m "chore: Auto-update dependencies and lockfile"
            echo "changes_exist=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Push changes
        # Only run if the commit step detected changes
        if: steps.commit.outputs.changes_exist == 'true'
        run: |
          echo "Pushing changes..."
          # Explicitly push to the branch the workflow is running on
          git push origin HEAD:${{ github.ref_name }}
