name: Update Dependencies

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2 AM UTC
  workflow_dispatch: # Optional manual trigger

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Update dependencies in package.json
        run: bunx npm-check-updates -u

      - name: Install updated dependencies and generate bun.lockb
        run: bun install

      - name: Commit and push changes
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Auto-update dependencies and lockfile" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
